#!/bin/bash
testPhase=$1
infectedTest=$2

temp=temp
mkdir -p temp
testOrderFile=$temp/bisect_test_order

echo "# Detecting test polution for $infectedTest..."
echo "# test phase: $testPhase"

grep testsuite target/test-reports/TESTS-TestSuites.xml | grep -v testsuites | cut -d\  -f8-9 | sed -E 's/name="(.*)" package="(.*)"/\2.\1/' | grep . > $testOrderFile
echo "# Running over test list:"
cat $testOrderFile

echo "# running bisection..."
bails/test/lib.bisect --testOrderFilePath=$testOrderFile --pollutedTest=$infectedTest --testPhase=$testPhase

