#!/bin/bash
# TODO run each file separately and process into target/plugins/frontlinesms-core/$ORIGINAL_PATH
# TODO load predefs from web-app/js global vars

TEMP_JS=target/temp.js
bails/lib/extract_js_from_gsps $@

echo "# Linting..."
bails/report/jslint $TEMP_JS
if [ -z "$@" ]; then
	# special case - these scripts are in GSPs but aren't enclosed in <r:script> tags.
	bails/report/jslint grails-app/views/webconnection/*/_scripts.gsp
fi
echo "# Lint complete."

