#!/bin/bash
#
# util
# ====
# BASH Library for utility functions.
# These functions should have no direct ties to a particular project or context.
temp=tmp

log() {
	local logStart="#"
	local sourceLen=${#BASH_SOURCE[@]}
	for ((i=$sourceLen-1; i>0; --i)); do
		if [[ $logStart != 'general' ]]; then
			logStart="$logStart [$(basename ${BASH_SOURCE[$i]})]"
		fi
	done
	echo "$logStart $@"
}

TODO() {
	echo "TODO: $@"
	exit 1
}

increment_version() {
	local previousVersion="$@"
	local newVersionHead=${previousVersion%.*}
	local newVersionTail=${previousVersion##*.}
	echo "${newVersionHead}.$(($newVersionTail + 1))"
}

confirm() {
	if [[ "$@" ]]; then
		echo "# $@"
	fi
	read -p "# Press [enter] to continue."
}

