#!/bin/bash
_grails_target=target
testReports=$_grails_target/test-reports
analysisReports=$_grails_target/analysis-reports

function grails_assert_no_snapshot_dependencies {
	log "Checking for SNAPSHOT dependencies..."
	local res=$(grep -Erq SNAPSHOT grails-app/conf/BuildConfig.groovy)
	if [[ $res == "0" ]]; then
		log "SNAPSHOT dependencies found."
		exit 1
	fi
	if [[ $res != "1" ]]; then
		log "No SNAPSHOT dependencies found."
		return
	fi
	log "Error checking for SNAPSHOT dependencies."
	exit $res
}

function groovy_get_var {
	local fileName=$1
	local varName=$2
	env groovy -e "$(grep "^\s*def $varName" $fileName); println $varName"
}

function grails_get_plugin_version {
	groovy_get_var '*GrailsPlugin.groovy' version
}

function grails_get_application_property {
	local key=$1
	grep "^$(echo $key | sed 's/\./\\./g')=" application.properties | cut -d= -f2
}

function grails_change_plugin_version {
	local _prev="$1"
	local _next="$2"
	sed -i -E -e "s/def\s+version\s*=\s*['\"]$_prev['\"]/def version = '$_next'/g" *GrailsPlugin.groovy
}

