#!/bin/bash
source bails/head

initScript=scripts/BailsInit.groovy
pluginVersion=$(grails_get_plugin_version)
pluginVersionInScript=$(groovy_get_var $initScript bailsVersion)

if [[ $pluginVersionInScript != $pluginVersion ]]; then
	log "Plugin version differs from that listed in $initScript.  Build will not work."
	log "Grails plugin version: $pluginVersion"
	log "In $initScript: $pluginVersionInScript"
	exit 1
fi

bails/plugin/build_deploy $@

