#!/bin/bash
source do/util

log "Current version is $(bails_get_version)."
log "$bailsInitScript version: $(bails_get_version_in_init_script)."
read -p "# If you are happy these version match, press [ENTER] to continue. "

bails/plugin/release $@

