#!/bin/bash
set -e
TARGET_DIR="target/analysis-reports"
TARGET="$TARGET_DIR/jslint.xml"
echo "# Generating jslint report in $TARGET ..."
mkdir -p $TARGET_DIR
bails/report/jslint --json | bails/report/lib.jslint/json_to_xml 'plugins/frontlinesms-core/' > $TARGET
echo "# Report generated in $TARGET"

